Repository CommitMentor/CoMentor-Frontend, pull requests merged in 2025-04, with the labels that each got.

#15 Docs/템플릿 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring.md
Labels: 📝 docs

#16 Fix: 모달 열릴 때 body 스크롤 방지 추가
  src/components/ProjectEditModal/index.tsx
  src/components/ProjectImportModal/index.tsx
Labels: 🚨fix

#18 Main
  .github/workflows/sync.yml
  next.config.mjs
  package-lock.json
  package.json
  src/app/(after)/bookmark/page.tsx
  src/app/(after)/user/page.tsx
  src/app/(before)/token/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/AuthSetting/token.tsx
  vercel.json
Labels: ⚙️chore, 🚨fix

#26 style: 레이아웃 수정
  src/app/(after)/user/page.tsx
  src/app/(before)/signup/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/EditForm/EditForm.tsx
  src/components/SignupForm/SignupForm.tsx
  src/components/onboarding/OnboardingPage.tsx
Labels: 👩🏻‍💻frontend, 🚨fix

#27 Feat/detailscreen
  package-lock.json
  package.json
  src/api/MSWComponent.tsx
  src/api/index.ts
  src/api/mocks/handlers/index.ts
  src/api/mocks/handlers/project.ts
  src/api/mocks/worker/browser.ts
  src/api/services/project.ts
  src/app/(after)/project/[projectId]/page.tsx
  src/app/(before)/auth/token/page.tsx
  src/app/globals.css
  src/components/Dashboard/Dashboard.tsx
  src/components/DashboardCard/CardContent.tsx
  src/components/DashboardCard/DashboardCard.tsx
  src/components/DetailProject/code-selection/CodeViewer.tsx
  src/components/DetailProject/code-selection/DateRangePicker.tsx
  src/components/DetailProject/code-selection/FileList.tsx
  src/components/DetailProject/code-selection/index.tsx
  src/components/DetailProject/code-selection/useCodeSelection.ts
  src/components/DetailProject/cs-questions/AnswerForm.tsx
  src/components/DetailProject/cs-questions/LearningInsights.tsx
  src/components/DetailProject/cs-questions/QuestionList.tsx
  src/components/DetailProject/cs-questions/index.tsx
  src/components/DetailProject/cs-questions/useCSQuestions.ts
  src/components/DetailProject/index.tsx
  src/components/DetailProject/question-history/HistoryList.tsx
  src/components/DetailProject/question-history/QuestionDetail.tsx
  src/components/DetailProject/question-history/index.tsx
  src/components/DetailProject/question-history/useQuestionHistory.ts
  src/components/DetailProject/types.ts
  src/components/DetailProject/ui/CodeSnippetViewer.tsx
  src/components/DetailProject/ui/ProjectHeader.tsx
  src/components/DetailProject/ui/QuestionCard.tsx
  src/components/MSWComponent.tsx
  src/components/ProjectEditModal/index.tsx
  src/components/ProjectImportModal/index.tsx
  src/components/ui/accordion.tsx
  src/components/ui/alert.tsx
  src/components/ui/card.tsx
  src/components/ui/progress.tsx
Labels: ✨ feat, ⚙️chore, 👩🏻‍💻frontend

#28 GitHub/code
  next.config.mjs
  src/api/index.ts
  src/api/lib/fetcher.ts
  src/api/services/github/githubService.ts
  src/app/(before)/auth/token/page.tsx
  src/app/github/page.tsx
  src/components/Github/github.tsx
  src/components/onboarding/OnboardingPage.tsx
  src/store/authStore.ts
Labels: ✨ feat

#29 Feat: 프로젝트 대시보드 페이지네이션 기능 구현
  src/api/mocks/handlers/project.ts
  src/api/services/project/index.ts
  src/components/Dashboard/Dashboard.tsx
Labels: ✨ feat, 👩🏻‍💻frontend

#31 Feat/projectinfo
  src/api/index.ts
  src/api/lib/fetcher.ts
  src/api/mocks/handlers/project.ts
  src/api/services/project.ts
  src/api/services/project/index.ts
  src/api/services/question/feedback.ts
  src/api/services/question/generate.ts
  src/api/services/question/history.ts
  src/api/services/question/query.ts
  src/api/services/question/types.ts
  src/components/Dashboard/Dashboard.tsx
  src/components/DashboardCard/DashboardCard.tsx
  src/components/DetailProject/code-selection/CodeViewer.tsx
  src/components/DetailProject/code-selection/FileList.tsx
  src/components/DetailProject/code-selection/index.tsx
  src/components/DetailProject/code-selection/useCodeSelection.ts
  src/components/DetailProject/cs-questions/QuestionList.tsx
  src/components/DetailProject/cs-questions/index.tsx
  src/components/DetailProject/cs-questions/useCSQuestions.ts
  src/components/DetailProject/index.tsx
  src/components/DetailProject/question-history/HistoryList.tsx
  src/components/DetailProject/question-history/QuestionDetail.tsx
  src/components/DetailProject/question-history/index.tsx
  src/components/DetailProject/question-history/useQuestionHistory.ts
  src/components/DetailProject/types.ts
  src/components/DetailProject/ui/QuestionCard.tsx
  src/components/EditForm/EditForm.tsx
  src/components/ProjectEditModal/index.tsx
  src/components/ProjectImportModal/index.tsx
Labels: ✨ feat

#35 Fix/GitHub 리포지토리 조회 훅 추가
  src/api/index.ts
Labels: 🚨fix

#38 Feat/질문기록 탭에서의 답변,피드백 기능 추가
  src/api/mocks/handlers/project.ts
  src/api/services/project.ts
  src/api/services/question/generate.ts
  src/api/services/question/types.ts
  src/app/globals.css
  src/components/DetailProject/code-selection/index.tsx
  src/components/DetailProject/code-selection/useCodeSelection.ts
  src/components/DetailProject/cs-questions/index.tsx
  src/components/DetailProject/cs-questions/useCSQuestions.ts
  src/components/DetailProject/index.tsx
  src/components/DetailProject/question-history/HistoryList.tsx
  src/components/DetailProject/question-history/QuestionDetail.tsx
  src/components/DetailProject/question-history/index.tsx
  src/components/DetailProject/question-history/useQuestionHistory.ts
  src/components/DetailProject/types.ts
  src/components/DetailProject/ui/QuestionCard.tsx
Labels: ✨ feat, 👩🏻‍💻frontend, 🚨fix

#41 Refactor/modeltype
  src/api/index.ts
  src/api/mocks/handlers/project.ts
  src/api/services/github/githubApi.ts
  src/api/services/github/githubRepo.ts
  src/api/services/github/projectGithubService.ts
  src/api/services/project/index.ts
  src/api/services/project/model.ts
  src/api/services/question/types.ts
  src/components/DetailProject/types.ts
  src/components/MSWComponent.tsx
Labels: 🪄refactor

#42 Feat/related code
  src/api/index.ts
  src/api/mocks/handlers/project.ts
  src/api/services/github/projectGithubService.ts
  src/api/services/project/model.ts
  src/api/services/question/query.ts
  src/components/DashboardCard/CardContent.tsx
  src/components/DetailProject/cs-questions/AnswerForm.tsx
  src/components/DetailProject/cs-questions/index.tsx
  src/components/DetailProject/cs-questions/useCSQuestions.ts
  src/components/DetailProject/question-history/HistoryList.tsx
  src/components/DetailProject/question-history/QuestionDetail.tsx
  src/components/DetailProject/question-history/useQuestionHistory.ts
  src/components/DetailProject/types.ts
  src/components/DetailProject/ui/ProjectHeader.tsx
  src/components/DetailProject/ui/QuestionCard.tsx
  src/utils/updated_date.ts
Labels: ✨ feat, 👩🏻‍💻frontend, 🪄refactor

#45 Feat/onboarding new
  package-lock.json
  package.json
  public/animations/coding-animation.json
  src/components/onboarding/OnboardingPage.tsx
  src/components/onboarding/components/FeatureCard.tsx
  src/components/onboarding/components/ModernIcon.tsx
  src/components/onboarding/constants.ts
  src/components/onboarding/sections/FeatureSection.tsx
  src/components/onboarding/sections/WelcomeSection.tsx
Labels: 👩🏻‍💻frontend
